EvenementVie.create({id: '1', nom: 'cloture des comptes', use_admi_facile: false})
EvenementVie.create({id: '2', nom: 'Commercialisation', use_admi_facile: false})
EvenementVie.create({id: '3', nom: 'conditions de travail', use_admi_facile: false})
EvenementVie.create({id: '4', nom: 'Construire des locaux', use_admi_facile: true})
EvenementVie.create({id: '5', nom: 'cotisations sociales', use_admi_facile: false})
EvenementVie.create({id: '6', nom: 'Création d\'entreprise', use_admi_facile: false})
EvenementVie.create({id: '7', nom: 'Declaration de possession', use_admi_facile: false})
EvenementVie.create({id: '8', nom: 'Demande d\'aide', use_admi_facile: true})
EvenementVie.create({id: '9', nom: 'Export / Import', use_admi_facile: false})
EvenementVie.create({id: '10', nom: 'Financements publics', use_admi_facile: true})
EvenementVie.create({id: '11', nom: 'formation du personnel', use_admi_facile: false})
EvenementVie.create({id: '12', nom: 'impots', use_admi_facile: false})
EvenementVie.create({id: '13', nom: 'indemnisation', use_admi_facile: false})
EvenementVie.create({id: '14', nom: 'Marchés publics', use_admi_facile: true})
EvenementVie.create({id: '15', nom: 'Modification des statuts', use_admi_facile: false})
EvenementVie.create({id: '16', nom: 'Normes et mesures environnementales', use_admi_facile: false})
EvenementVie.create({id: '17', nom: 'Procédure judiciaire', use_admi_facile: false})
EvenementVie.create({id: '18', nom: 'protection innovation', use_admi_facile: false})
EvenementVie.create({id: '19', nom: 'Publication officielle', use_admi_facile: false})
EvenementVie.create({id: '20', nom: 'recrutement du personnel', use_admi_facile: false})
EvenementVie.create({id: '21', nom: 'remunération du personnel', use_admi_facile: false})
EvenementVie.create({id: '22', nom: 'se séparer d\'un salarié', use_admi_facile: false})