en:
  users:
    procedure_footer:
      contact:
        email:
          link: "By email %{service_email}"
      legals:
        data_retention: "%{application_name} will keep your file: %{duree_conservation_dossiers_dans_ds} months"
      dematerialisation:
        link: "https://www.service-public.pf/demarches-en-ligne/"
        title_2: Trouver une démarche
        alt: Find a procedure
  views:
    legal_notice:
      title: "Legal Notices"
      editing: "Editor"
      editing_content:
        line_one: "Direction of Modernization and Reforms of Administration of French Polynesia (DMRA)"
        line_two: "Phone : 40.47.24.60 - Mail : secretariat@modernisation.gov.pf"
        line_three: "BP 2551 - 98713 Papeete, French Polynesia"
      direction: "Publishing director"
      direction_content: "Mr. Eric DEAT, Director of Modernization and Reforms of Administration of French Polynesia."
      hosting: "Hosting provider"
      hosting_content:
        line_one: "Direction of Information Systems of french Polynésia (DSI)"
        line_two: "TAHITI number 004507 001"
        line_three: "Phone : (689) 40.54.43.54 - Mail : secretariat@informatique.gov.pf"
        line_four: "BP 4574- 98713 Papeete Tahiti French Polynesia"
        line_five: "Immeuble Toriki, Rue Dumont d’Urville, 98713 Papeete, French Polynesia"
    accessibility_statement:
      line_one: "DINUM is committed to making this service accessible in accordance with Article 47 of Law No. 2005-102 of 11 February 2005."
      line_two: "This accessibility statement applies to %{app_name} (%{host}), which is based on Démarches-Simplifiées.fr site."
      compliance:
        line_one_html: "The Mes-Démarches website is <strong>partially compliant</strong> with the General Accessibility Guidelines (RGAA) version 4."
      results:
        title: "Test results"
        line_one: "As of 1 April 2023, the site's average compliance rate is 75%."
        programme:
          label: "Follow the Mes-Démarches/Démarches-Simplifiées accessibility continuous improvement programme"
          title: "Follow the Mes-Démarches/Démarches-Simplifiées accessibility continuous improvement programme - new tab"
      preparation:
        title: "Preparation of this accessibility statement"
        intro: "This statement was drawn up on April 27, 2022. It was updated on April 1, 2023."
        environment_intro: "The content rendering tests were carried out on the basis of a combination provided by the RGAA reference base, with the following versions:"
        subtitle_four: "Pages of the site checked for compliance"
      contact:
        intro: "If you are unable to access a specific area of the website, you can contact manager of Mes-Démarches to be directed to an accessible alternative or to get the content in another form."
        infos:
          email_html: "By email:"
          phone_html: "Contact DMRA by phone:"
          adress_html: "By mail : BP 2551 - 98713 Papeete, French Polynesia"
      remedies:
        line_one: "If you report tu us a lack of accessibility that prevents you from accessing any content or functionality of the site, and do not manage to receive a rapid response from us, you are entitled to send your complaints or a request for referral to the Rights Defender."
        remedies_three: "Send a letter by mail (free of charge, no stamp) at Défenseur des droits Libre réponse 71120 75342 Paris CEDEX 07"

