fr:
  users:
    procedure_footer:
      contact:
        email:
          link: "Par courriel : %{service_email}"
      legals:
        data_retention: "%{application_name} conservera ce dossier : %{duree_conservation_dossiers_dans_ds} mois"
      dematerialisation:
        link: "https://www.service-public.pf/demarches-en-ligne/"
  views:
    legal_notice:
      title: "Mentions légales"
      editing: "Éditeur"
      editing_content:
        line_one: "Direction de la modernisation et des réformes de l’administration de la Polynésie française (DMRA)"
        line_two: "Tel : 40.47.24.60 - Courriel : secretariat@modernisation.gov.pf"
        line_three: "BP 2551 - 98713 Papeete"
      direction: "Direction de la publication"
      direction_content: "Monsieur Eric DEAT, Directeur de la modernisation et des réformes de l’administration de la Polynésie française."
      hosting: "Prestataire d'hébergement"
      hosting_content:
        line_one: "Direction du système d’information de la Polynésie française (DSI)"
        line_two: "Numéro TAHITI 004507 001"
        line_three: "Téléphone : (689) 40.54.43.54 - Courriel : secretariat@informatique.gov.pf"
        line_four: "BP 4574- 98713 Papeete Tahiti Polynésie française"
        line_five: "Immeuble Toriki, Rue Dumont d’Urville, 98713 Papeete, Polynésie française"
    accessibility_statement:
      line_two: "Cette déclaration d’accessibilité s’applique à %{app_name} (%{host}) qui est basé sur le site de Démarches-Simplifiées.fr."
      compliance:
        line_one_html: "Le site Mes-Démarches est <strong>partiellement conforme</strong> avec le référentiel général d’amélioration de l’accessibilité (RGAA) version 4."
      results:
        programme:
          label: "Suivez le programme d'amélioration continue de Démarches-Simplifiées en matière d'accessibilité"
          title: "Suivez le programme d'amélioration continue de Démarches-Simplifiées en matière d'accessibilité - nouvel onglet"
      contact:
        intro: "Si vous n’arrivez pas à accéder à un contenu ou à un service, vous pouvez contacter le responsable de Mes-Démarches pour être orienté vers une alternative accessible ou obtenir le contenu sous une autre forme."
        infos:
          phone_html: "Contacter la DMRA par téléphone :"
          adress_html: "Par voie postale : DMRA, BP 2551 - 98713 Papeete"

