spectaql:
  displayAllServers: true
  targetDir: public/graphql/schema

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: app/graphql/schema.graphql

extensions:
  graphqlScalarExamples: true

info:
  title: Schema de l'API GraphQL de demarches-simplifiees.fr
  description: détails des apis
  contact:
    name: équipe support
    url: https://doc.demarches-simplifiees.fr/api-graphql
    email: contact@demarches-simplifiees.fr

servers:
  - url: https://www.demarches-simplifiees.fr/api/v2/graphql
    description: Production
    production: true
    headers:
      - name: Authorization
        example: Bearer <YOUR_TOKEN_HERE>
        comment: Create your token in https://www.demarches-simplifiees.fr/profil
