en:
  users:
    procedure_footer:
      contact:
        email:
          link: "By email %{service_email}"
      legals:
        data_retention: "%{application_name} will keep your file: %{duree_conservation_dossiers_dans_ds} months"
      dematerialisation:
        link: "https://www.service-public.pf/demarches-en-ligne/"
