class Dsfr::ComboboxComponentPreview < ViewComponent::Preview
  OPTIONS = [
    'Cheddar',
    'Brie',
    'Mozzarella',
    'Gouda',
    'Swiss',
    'Parmesan',
    'Feta',
    'Blue cheese',
    'Camembert',
    'Monterey Jack',
    'Roquefort',
    'Provolone',
    'Colby',
    'Havarti',
    'Ricotta',
    'Pepper Jack',
    'Muenster',
    'Fontina',
    'Limburger',
    'Asiago',
    'Cottage cheese',
    'Emmental',
    'Mascarpone',
    'Taleggio',
    'Gruyere',
    'Edam',
    'Pecorino Romano',
    'Manchego',
    'Halloumi',
    'Jarlsberg',
    'Munster',
    'Stilton',
    'Gorgonzola',
    'Queso blanco',
    'Queso fresco',
    'Queso de bola',
    'Queso de cabra',
    'Queso panela',
    'Queso Oaxaca',
    'Queso Chihuahua',
    'Queso manchego',
    'Queso de bola',
    'Queso de bola de cabra',
    'Queso de bola de vaca',
    'Queso de bola de oveja',
    'Queso de bola de mezcla',
    'Queso de bola de leche cruda',
    'Queso de bola de leche pasteurizada',
    'Queso de bola de leche de cabra',
    'Queso de bola de leche de vaca',
    'Queso de bola de leche de oveja',
    'Queso de bola de leche de mezcla',
    'Burrata',
    'Scamorza',
    'Caciocavallo',
    'Provolone piccante',
    'Pecorino sardo',
    'Pecorino toscano',
    'Pecorino siciliano',
    'Pecorino calabrese',
    'Pecorino moliterno',
    'Pecorino di fossa',
    'Pecorino di filiano',
    'Pecorino di pienza',
    'Pecorino di grotta',
    'Pecorino di capra',
    'Pecorino di mucca',
    'Pecorino di pecora',
    'Pecorino di bufala',
    'Cacio di bosco',
    'Cacio di roma',
    'Cacio di fossa',
    'Cacio di tricarico',
    'Cacio di cavallo',
    'Cacio di capra',
    'Cacio di mucca',
    'Cacio di pecora',
    'Cacio di bufala',
    'Taleggio di capra',
    'Taleggio di mucca',
    'Taleggio di pecora',
    'Taleggio di bufala',
    'Bel Paese',
    'Crescenza',
    'Stracchino',
    'Robiola',
    'Toma',
    'Bra',
    'Castelmagno',
    'Raschera',
    'Montasio',
    'Piave',
    'Bitto',
    'Quartirolo Lombardo',
    'Formaggella del Luinese',
    'Formaggella della Val Vigezzo',
    'Formaggella della Valle Grana',
    'Formaggella della Val Bognanco',
    'Formaggella della Val d’Intelvi',
    'Formaggella della Val Gerola'
  ]

  def simple_select_with_options
    render Dsfr::ComboboxComponent.new(options: OPTIONS, selected: OPTIONS.sample, input_html_options: { name: :value, id: 'simple-select', class: 'width-33' })
  end

  def simple_select_with_options_and_allows_custom_value
    render Dsfr::ComboboxComponent.new(options: OPTIONS, selected: OPTIONS.sample, allows_custom_value: true, input_html_options: { id: 'simple-select', class: 'width-33', name: :value })
  end
end
