APPLICATION_NAME = ENV.fetch("APPLICATION_NAME", "mes-demarches.gov.pf")
APPLICATION_SHORTNAME = ENV.fetch("APPLICATION_SHORTNAME", "MD")
APPLICATION_BASE_URL = ENV.fetch("APPLICATION_BASE_URL", "https://www.mes-demarches.gov.pf")
