# frozen_string_literal: true

class UpdateDatetimePrecision < ActiveRecord::Migration[7.0]
  def up
    safety_assured do
      change_column :action_text_rich_texts, :created_at, :datetime, precision: 6
      change_column :action_text_rich_texts, :updated_at, :datetime, precision: 6
      change_column :active_storage_attachments, :created_at, :datetime, precision: 6
      change_column :active_storage_blobs, :created_at, :datetime, precision: 6
      change_column :active_storage_blobs, :virus_scanned_at, :datetime, precision: 6
      change_column :active_storage_blobs, :watermarked_at, :datetime, precision: 6
      change_column :administrateurs, :created_at, :datetime, precision: 6
      change_column :administrateurs, :updated_at, :datetime, precision: 6
      change_column :administrateurs_instructeurs, :created_at, :datetime, precision: 6
      change_column :administrateurs_instructeurs, :updated_at, :datetime, precision: 6
      change_column :administrateurs_procedures, :created_at, :datetime, precision: 6
      change_column :administrateurs_procedures, :updated_at, :datetime, precision: 6
      change_column :assign_tos, :created_at, :datetime, precision: 6
      change_column :assign_tos, :updated_at, :datetime, precision: 6
      change_column :attestation_templates, :created_at, :datetime, precision: 6
      change_column :attestation_templates, :updated_at, :datetime, precision: 6
      change_column :attestations, :created_at, :datetime, precision: 6
      change_column :attestations, :updated_at, :datetime, precision: 6
      change_column :avis, :created_at, :datetime, precision: 6
      change_column :avis, :reminded_at, :datetime, precision: 6
      change_column :avis, :revoked_at, :datetime, precision: 6
      change_column :avis, :updated_at, :datetime, precision: 6
      change_column :batch_operations, :finished_at, :datetime, precision: 6
      change_column :batch_operations, :run_at, :datetime, precision: 6
      change_column :batch_operations, :seen_at, :datetime, precision: 6
      change_column :bill_signatures, :created_at, :datetime, precision: 6
      change_column :bill_signatures, :updated_at, :datetime, precision: 6
      change_column :bulk_messages, :sent_at, :datetime, precision: 6
      change_column :champs, :created_at, :datetime, precision: 6
      change_column :champs, :rebased_at, :datetime, precision: 6
      change_column :champs, :updated_at, :datetime, precision: 6
      change_column :closed_mails, :created_at, :datetime, precision: 6
      change_column :closed_mails, :updated_at, :datetime, precision: 6
      change_column :commentaires, :created_at, :datetime, precision: 6
      change_column :commentaires, :discarded_at, :datetime, precision: 6
      change_column :commentaires, :updated_at, :datetime, precision: 6
      change_column :delayed_jobs, :created_at, :datetime, precision: 6
      change_column :delayed_jobs, :failed_at, :datetime, precision: 6
      change_column :delayed_jobs, :locked_at, :datetime, precision: 6
      change_column :delayed_jobs, :run_at, :datetime, precision: 6
      change_column :delayed_jobs, :updated_at, :datetime, precision: 6
      change_column :deleted_dossiers, :created_at, :datetime, precision: 6
      change_column :deleted_dossiers, :deleted_at, :datetime, precision: 6
      change_column :deleted_dossiers, :updated_at, :datetime, precision: 6
      change_column :dossier_operation_logs, :created_at, :datetime, precision: 6
      change_column :dossier_operation_logs, :executed_at, :datetime, precision: 6
      change_column :dossier_operation_logs, :keep_until, :datetime, precision: 6
      change_column :dossier_operation_logs, :updated_at, :datetime, precision: 6
      change_column :dossiers, :archived_at, :datetime, precision: 6
      change_column :dossiers, :brouillon_close_to_expiration_notice_sent_at, :datetime, precision: 6
      change_column :dossiers, :created_at, :datetime, precision: 6
      change_column :dossiers, :declarative_triggered_at, :datetime, precision: 6
      change_column :dossiers, :depose_at, :datetime, precision: 6
      change_column :dossiers, :en_construction_at, :datetime, precision: 6
      change_column :dossiers, :en_construction_close_to_expiration_notice_sent_at, :datetime, precision: 6
      change_column :dossiers, :en_instruction_at, :datetime, precision: 6
      change_column :dossiers, :groupe_instructeur_updated_at, :datetime, precision: 6
      change_column :dossiers, :hidden_at, :datetime, precision: 6
      change_column :dossiers, :hidden_by_administration_at, :datetime, precision: 6
      change_column :dossiers, :hidden_by_user_at, :datetime, precision: 6
      change_column :dossiers, :identity_updated_at, :datetime, precision: 6
      change_column :dossiers, :last_avis_updated_at, :datetime, precision: 6
      change_column :dossiers, :last_champ_private_updated_at, :datetime, precision: 6
      change_column :dossiers, :last_champ_updated_at, :datetime, precision: 6
      change_column :dossiers, :last_commentaire_updated_at, :datetime, precision: 6
      change_column :dossiers, :processed_at, :datetime, precision: 6
      change_column :dossiers, :termine_close_to_expiration_notice_sent_at, :datetime, precision: 6
      change_column :dossiers, :updated_at, :datetime, precision: 6
      change_column :email_events, :processed_at, :datetime, precision: 6
      change_column :etablissements, :created_at, :datetime, precision: 6
      change_column :etablissements, :updated_at, :datetime, precision: 6
      change_column :exercices, :created_at, :datetime, precision: 6
      change_column :exercices, :dateFinExercice, :datetime, precision: 6
      change_column :exercices, :date_fin_exercice, :datetime, precision: 6
      change_column :exercices, :updated_at, :datetime, precision: 6
      change_column :experts_procedures, :revoked_at, :datetime, precision: 6
      change_column :exports, :created_at, :datetime, precision: 6
      change_column :exports, :updated_at, :datetime, precision: 6
      change_column :exports_groupe_instructeurs, :created_at, :datetime, precision: 6
      change_column :exports_groupe_instructeurs, :updated_at, :datetime, precision: 6
      change_column :flipper_features, :created_at, :datetime, precision: 6
      change_column :flipper_features, :updated_at, :datetime, precision: 6
      change_column :flipper_gates, :created_at, :datetime, precision: 6
      change_column :flipper_gates, :updated_at, :datetime, precision: 6
      change_column :follows, :annotations_privees_seen_at, :datetime, precision: 6
      change_column :follows, :avis_seen_at, :datetime, precision: 6
      change_column :follows, :created_at, :datetime, precision: 6
      change_column :follows, :demande_seen_at, :datetime, precision: 6
      change_column :follows, :messagerie_seen_at, :datetime, precision: 6
      change_column :follows, :unfollowed_at, :datetime, precision: 6
      change_column :follows, :updated_at, :datetime, precision: 6
      change_column :france_connect_informations, :created_at, :datetime, precision: 6
      change_column :france_connect_informations, :merge_token_created_at, :datetime, precision: 6
      change_column :france_connect_informations, :updated_at, :datetime, precision: 6
      change_column :geo_areas, :created_at, :datetime, precision: 6
      change_column :geo_areas, :updated_at, :datetime, precision: 6
      change_column :groupe_instructeurs, :created_at, :datetime, precision: 6
      change_column :groupe_instructeurs, :updated_at, :datetime, precision: 6
      change_column :individuals, :created_at, :datetime, precision: 6
      change_column :individuals, :updated_at, :datetime, precision: 6
      change_column :initiated_mails, :created_at, :datetime, precision: 6
      change_column :initiated_mails, :updated_at, :datetime, precision: 6
      change_column :instructeurs, :created_at, :datetime, precision: 6
      change_column :instructeurs, :login_token_created_at, :datetime, precision: 6
      change_column :instructeurs, :updated_at, :datetime, precision: 6
      change_column :invites, :created_at, :datetime, precision: 6
      change_column :invites, :updated_at, :datetime, precision: 6
      change_column :module_api_cartos, :created_at, :datetime, precision: 6
      change_column :module_api_cartos, :updated_at, :datetime, precision: 6
      change_column :procedure_presentations, :created_at, :datetime, precision: 6
      change_column :procedure_presentations, :updated_at, :datetime, precision: 6
      change_column :procedure_revision_types_de_champ, :created_at, :datetime, precision: 6
      change_column :procedure_revision_types_de_champ, :updated_at, :datetime, precision: 6
      change_column :procedure_revisions, :created_at, :datetime, precision: 6
      change_column :procedure_revisions, :published_at, :datetime, precision: 6
      change_column :procedure_revisions, :updated_at, :datetime, precision: 6
      change_column :procedures, :closed_at, :datetime, precision: 6
      change_column :procedures, :created_at, :datetime, precision: 6
      change_column :procedures, :dossiers_count_computed_at, :datetime, precision: 6
      change_column :procedures, :hidden_at, :datetime, precision: 6
      change_column :procedures, :published_at, :datetime, precision: 6
      change_column :procedures, :test_started_at, :datetime, precision: 6
      change_column :procedures, :unpublished_at, :datetime, precision: 6
      change_column :procedures, :updated_at, :datetime, precision: 6
      change_column :procedures, :whitelisted_at, :datetime, precision: 6
      change_column :received_mails, :created_at, :datetime, precision: 6
      change_column :received_mails, :updated_at, :datetime, precision: 6
      change_column :refused_mails, :created_at, :datetime, precision: 6
      change_column :refused_mails, :updated_at, :datetime, precision: 6
      change_column :services, :created_at, :datetime, precision: 6
      change_column :services, :updated_at, :datetime, precision: 6
      change_column :super_admins, :created_at, :datetime, precision: 6
      change_column :super_admins, :current_sign_in_at, :datetime, precision: 6
      change_column :super_admins, :last_sign_in_at, :datetime, precision: 6
      change_column :super_admins, :locked_at, :datetime, precision: 6
      change_column :super_admins, :remember_created_at, :datetime, precision: 6
      change_column :super_admins, :reset_password_sent_at, :datetime, precision: 6
      change_column :super_admins, :updated_at, :datetime, precision: 6
      change_column :traitements, :processed_at, :datetime, precision: 6
      change_column :trusted_device_tokens, :created_at, :datetime, precision: 6
      change_column :trusted_device_tokens, :updated_at, :datetime, precision: 6
      change_column :types_de_champ, :created_at, :datetime, precision: 6
      change_column :types_de_champ, :updated_at, :datetime, precision: 6
      change_column :users, :confirmation_sent_at, :datetime, precision: 6
      change_column :users, :confirmed_at, :datetime, precision: 6
      change_column :users, :created_at, :datetime, precision: 6
      change_column :users, :current_sign_in_at, :datetime, precision: 6
      change_column :users, :last_sign_in_at, :datetime, precision: 6
      change_column :users, :locked_at, :datetime, precision: 6
      change_column :users, :remember_created_at, :datetime, precision: 6
      change_column :users, :reset_password_sent_at, :datetime, precision: 6
      change_column :users, :updated_at, :datetime, precision: 6
      change_column :virus_scans, :created_at, :datetime, precision: 6
      change_column :virus_scans, :scanned_at, :datetime, precision: 6
      change_column :virus_scans, :updated_at, :datetime, precision: 6
      change_column :without_continuation_mails, :created_at, :datetime, precision: 6
      change_column :without_continuation_mails, :updated_at, :datetime, precision: 6
    end
  end

  def down
    safety_assured do
      change_column :action_text_rich_texts, :created_at, :datetime, precision: nil
      change_column :action_text_rich_texts, :updated_at, :datetime, precision: nil
      change_column :active_storage_attachments, :created_at, :datetime, precision: nil
      change_column :active_storage_blobs, :created_at, :datetime, precision: nil
      change_column :active_storage_blobs, :virus_scanned_at, :datetime, precision: nil
      change_column :active_storage_blobs, :watermarked_at, :datetime, precision: nil
      change_column :administrateurs, :created_at, :datetime, precision: nil
      change_column :administrateurs, :updated_at, :datetime, precision: nil
      change_column :administrateurs_instructeurs, :created_at, :datetime, precision: nil
      change_column :administrateurs_instructeurs, :updated_at, :datetime, precision: nil
      change_column :administrateurs_procedures, :created_at, :datetime, precision: nil
      change_column :administrateurs_procedures, :updated_at, :datetime, precision: nil
      change_column :assign_tos, :created_at, :datetime, precision: nil
      change_column :assign_tos, :updated_at, :datetime, precision: nil
      change_column :attestation_templates, :created_at, :datetime, precision: nil
      change_column :attestation_templates, :updated_at, :datetime, precision: nil
      change_column :attestations, :created_at, :datetime, precision: nil
      change_column :attestations, :updated_at, :datetime, precision: nil
      change_column :avis, :created_at, :datetime, precision: nil
      change_column :avis, :reminded_at, :datetime, precision: nil
      change_column :avis, :revoked_at, :datetime, precision: nil
      change_column :avis, :updated_at, :datetime, precision: nil
      change_column :batch_operations, :finished_at, :datetime, precision: nil
      change_column :batch_operations, :run_at, :datetime, precision: nil
      change_column :batch_operations, :seen_at, :datetime, precision: nil
      change_column :bill_signatures, :created_at, :datetime, precision: nil
      change_column :bill_signatures, :updated_at, :datetime, precision: nil
      change_column :bulk_messages, :sent_at, :datetime, precision: nil
      change_column :champs, :created_at, :datetime, precision: nil
      change_column :champs, :rebased_at, :datetime, precision: nil
      change_column :champs, :updated_at, :datetime, precision: nil
      change_column :closed_mails, :created_at, :datetime, precision: nil
      change_column :closed_mails, :updated_at, :datetime, precision: nil
      change_column :commentaires, :created_at, :datetime, precision: nil
      change_column :commentaires, :discarded_at, :datetime, precision: nil
      change_column :commentaires, :updated_at, :datetime, precision: nil
      change_column :delayed_jobs, :created_at, :datetime, precision: nil
      change_column :delayed_jobs, :failed_at, :datetime, precision: nil
      change_column :delayed_jobs, :locked_at, :datetime, precision: nil
      change_column :delayed_jobs, :run_at, :datetime, precision: nil
      change_column :delayed_jobs, :updated_at, :datetime, precision: nil
      change_column :deleted_dossiers, :created_at, :datetime, precision: nil
      change_column :deleted_dossiers, :deleted_at, :datetime, precision: nil
      change_column :deleted_dossiers, :updated_at, :datetime, precision: nil
      change_column :dossier_operation_logs, :created_at, :datetime, precision: nil
      change_column :dossier_operation_logs, :executed_at, :datetime, precision: nil
      change_column :dossier_operation_logs, :keep_until, :datetime, precision: nil
      change_column :dossier_operation_logs, :updated_at, :datetime, precision: nil
      change_column :dossiers, :archived_at, :datetime, precision: nil
      change_column :dossiers, :brouillon_close_to_expiration_notice_sent_at, :datetime, precision: nil
      change_column :dossiers, :created_at, :datetime, precision: nil
      change_column :dossiers, :declarative_triggered_at, :datetime, precision: nil
      change_column :dossiers, :depose_at, :datetime, precision: nil
      change_column :dossiers, :en_construction_at, :datetime, precision: nil
      change_column :dossiers, :en_construction_close_to_expiration_notice_sent_at, :datetime, precision: nil
      change_column :dossiers, :en_instruction_at, :datetime, precision: nil
      change_column :dossiers, :groupe_instructeur_updated_at, :datetime, precision: nil
      change_column :dossiers, :hidden_at, :datetime, precision: nil
      change_column :dossiers, :hidden_by_administration_at, :datetime, precision: nil
      change_column :dossiers, :hidden_by_user_at, :datetime, precision: nil
      change_column :dossiers, :identity_updated_at, :datetime, precision: nil
      change_column :dossiers, :last_avis_updated_at, :datetime, precision: nil
      change_column :dossiers, :last_champ_private_updated_at, :datetime, precision: nil
      change_column :dossiers, :last_champ_updated_at, :datetime, precision: nil
      change_column :dossiers, :last_commentaire_updated_at, :datetime, precision: nil
      change_column :dossiers, :processed_at, :datetime, precision: nil
      change_column :dossiers, :termine_close_to_expiration_notice_sent_at, :datetime, precision: nil
      change_column :dossiers, :updated_at, :datetime, precision: nil
      change_column :email_events, :processed_at, :datetime, precision: nil
      change_column :etablissements, :created_at, :datetime, precision: nil
      change_column :etablissements, :updated_at, :datetime, precision: nil
      change_column :exercices, :created_at, :datetime, precision: nil
      change_column :exercices, :dateFinExercice, :datetime, precision: nil
      change_column :exercices, :date_fin_exercice, :datetime, precision: nil
      change_column :exercices, :updated_at, :datetime, precision: nil
      change_column :experts_procedures, :revoked_at, :datetime, precision: nil
      change_column :exports, :created_at, :datetime, precision: nil
      change_column :exports, :updated_at, :datetime, precision: nil
      change_column :exports_groupe_instructeurs, :created_at, :datetime, precision: nil
      change_column :exports_groupe_instructeurs, :updated_at, :datetime, precision: nil
      change_column :flipper_features, :created_at, :datetime, precision: nil
      change_column :flipper_features, :updated_at, :datetime, precision: nil
      change_column :flipper_gates, :created_at, :datetime, precision: nil
      change_column :flipper_gates, :updated_at, :datetime, precision: nil
      change_column :follows, :annotations_privees_seen_at, :datetime, precision: nil
      change_column :follows, :avis_seen_at, :datetime, precision: nil
      change_column :follows, :created_at, :datetime, precision: nil
      change_column :follows, :demande_seen_at, :datetime, precision: nil
      change_column :follows, :messagerie_seen_at, :datetime, precision: nil
      change_column :follows, :unfollowed_at, :datetime, precision: nil
      change_column :follows, :updated_at, :datetime, precision: nil
      change_column :france_connect_informations, :created_at, :datetime, precision: nil
      change_column :france_connect_informations, :merge_token_created_at, :datetime, precision: nil
      change_column :france_connect_informations, :updated_at, :datetime, precision: nil
      change_column :geo_areas, :created_at, :datetime, precision: nil
      change_column :geo_areas, :updated_at, :datetime, precision: nil
      change_column :groupe_instructeurs, :created_at, :datetime, precision: nil
      change_column :groupe_instructeurs, :updated_at, :datetime, precision: nil
      change_column :individuals, :created_at, :datetime, precision: nil
      change_column :individuals, :updated_at, :datetime, precision: nil
      change_column :initiated_mails, :created_at, :datetime, precision: nil
      change_column :initiated_mails, :updated_at, :datetime, precision: nil
      change_column :instructeurs, :created_at, :datetime, precision: nil
      change_column :instructeurs, :login_token_created_at, :datetime, precision: nil
      change_column :instructeurs, :updated_at, :datetime, precision: nil
      change_column :invites, :created_at, :datetime, precision: nil
      change_column :invites, :updated_at, :datetime, precision: nil
      change_column :module_api_cartos, :created_at, :datetime, precision: nil
      change_column :module_api_cartos, :updated_at, :datetime, precision: nil
      change_column :procedure_presentations, :created_at, :datetime, precision: nil
      change_column :procedure_presentations, :updated_at, :datetime, precision: nil
      change_column :procedure_revision_types_de_champ, :created_at, :datetime, precision: nil
      change_column :procedure_revision_types_de_champ, :updated_at, :datetime, precision: nil
      change_column :procedure_revisions, :created_at, :datetime, precision: nil
      change_column :procedure_revisions, :published_at, :datetime, precision: nil
      change_column :procedure_revisions, :updated_at, :datetime, precision: nil
      change_column :procedures, :closed_at, :datetime, precision: nil
      change_column :procedures, :created_at, :datetime, precision: nil
      change_column :procedures, :dossiers_count_computed_at, :datetime, precision: nil
      change_column :procedures, :hidden_at, :datetime, precision: nil
      change_column :procedures, :published_at, :datetime, precision: nil
      change_column :procedures, :test_started_at, :datetime, precision: nil
      change_column :procedures, :unpublished_at, :datetime, precision: nil
      change_column :procedures, :updated_at, :datetime, precision: nil
      change_column :procedures, :whitelisted_at, :datetime, precision: nil
      change_column :received_mails, :created_at, :datetime, precision: nil
      change_column :received_mails, :updated_at, :datetime, precision: nil
      change_column :refused_mails, :created_at, :datetime, precision: nil
      change_column :refused_mails, :updated_at, :datetime, precision: nil
      change_column :services, :created_at, :datetime, precision: nil
      change_column :services, :updated_at, :datetime, precision: nil
      change_column :super_admins, :created_at, :datetime, precision: nil
      change_column :super_admins, :current_sign_in_at, :datetime, precision: nil
      change_column :super_admins, :last_sign_in_at, :datetime, precision: nil
      change_column :super_admins, :locked_at, :datetime, precision: nil
      change_column :super_admins, :remember_created_at, :datetime, precision: nil
      change_column :super_admins, :reset_password_sent_at, :datetime, precision: nil
      change_column :super_admins, :updated_at, :datetime, precision: nil
      change_column :traitements, :processed_at, :datetime, precision: nil
      change_column :trusted_device_tokens, :created_at, :datetime, precision: nil
      change_column :trusted_device_tokens, :updated_at, :datetime, precision: nil
      change_column :types_de_champ, :created_at, :datetime, precision: nil
      change_column :types_de_champ, :updated_at, :datetime, precision: nil
      change_column :users, :confirmation_sent_at, :datetime, precision: nil
      change_column :users, :confirmed_at, :datetime, precision: nil
      change_column :users, :created_at, :datetime, precision: nil
      change_column :users, :current_sign_in_at, :datetime, precision: nil
      change_column :users, :last_sign_in_at, :datetime, precision: nil
      change_column :users, :locked_at, :datetime, precision: nil
      change_column :users, :remember_created_at, :datetime, precision: nil
      change_column :users, :reset_password_sent_at, :datetime, precision: nil
      change_column :users, :updated_at, :datetime, precision: nil
      change_column :virus_scans, :created_at, :datetime, precision: nil
      change_column :virus_scans, :scanned_at, :datetime, precision: nil
      change_column :virus_scans, :updated_at, :datetime, precision: nil
      change_column :without_continuation_mails, :created_at, :datetime, precision: nil
      change_column :without_continuation_mails, :updated_at, :datetime, precision: nil
    end
  end
end
