fr:
  users:
    procedure_footer:
      contact:
        email:
          link: "Par courriel : %{service_email}"
      legals:
        data_retention: "%{application_name} conservera ce dossier : %{duree_conservation_dossiers_dans_ds} mois"
      dematerialisation:
        link: "https://www.service-public.pf/demarches-en-ligne/"
