name: 'Setup Rails app'
description: 'Setup the environment for running the Rails app'

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Install Node modules
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Setup environment variables
      run: cp config/env.example .env
      shell: bash

    - name: Setup test database
      env:
        RAILS_ENV: test
        DATABASE_URL: "postgres://tps_test@localhost:5432/tps_test"
      run: bin/rails db:create db:schema:load db:migrate
      shell: bash

    - name: Setup split_tests binary
      run: |
        curl --no-progress-meter -L https://github.com/leonid-shevtsov/split_tests/releases/download/v0.3.0/split_tests.linux.gz | gunzip -c > split_tests
        chmod +x split_tests
      shell: bash
