name: 'Setup Rails app'
description: 'Setup the environment for running the Rails app'

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Setup environment variables
      run: cp config/env.example .env
      shell: bash

    - name: Setup test database
      env:
        RAILS_ENV: test
        DATABASE_URL: 'postgres://tps_test@localhost:5432/tps_test'
      run: bin/rails db:schema:load db:migrate
      shell: bash
